### ISSUE TITLE
very high cpu usage when countdown is enabled

### ISSUE THREAD

**Issue by rmobis** [rahji/TheFilenalCountdown#3]
I came across this program on the OBS forums and it is really useful indeed, I appreciate your work. However, I noticed that it seems to be using a more than fair amount of CPU time, by looking at my task manager.

![image](https://user-images.githubusercontent.com/2119933/99473330-21a82e00-2929-11eb-9089-c31eacfb9378.png)

It usually goes to about 15-18%, which is close to the 16.6% I'd expect if were running nonstop on one of the 8 cores of my PC. So I'm guessing there's probably some loop needing a sleep? I'll see if I can get a PR on it.

**Comment by rahji** [comment]
Thanks @rmobis - it seems like this solution is more of a workaround and the application should probably be rewritten to use a separate thread instead of piggybacking on the UI thread. This seems to work, though, so I'm happy. It's been pulled and has become The Filenal Countdown v1.3
